@startuml
actor User #red
User -> ReactActivity: 1 onCreate
ReactActivity -> ReactActivityDelegate: 2 onCreate
ReactActivityDelegate -> ReactActivityDelegate: 3 loadApp
ReactActivityDelegate -> ReactNativeHost: 4 getReactInstanceManager
ReactNativeHost -> ReactNativeHost: 5 createReactInstanceManager
ReactNativeHost -> ReactInstanceManager: builder
ReactInstanceManager -> ReactInstanceManagerBuilder: builder
ReactActivityDelegate -> ReactActivityDelegate: 创建 RootView
ReactActivityDelegate -> ReactActivityDelegate: mReactRootView.startReactApplication
ReactActivityDelegate -> ReactActivityDelegate: 将 ReactRootView 添加到 Activity


@enduml