@startuml
actor User

User -> TXLivePlayer: startPlay
TXLivePlayer -> TXLivePlayerImpDelegate: a
TXLivePlayerImpDelegate -> TXLivePlayerImp: a
TXLivePlayerImp -> TXCStreamDownloader: start
TXCStreamDownloader -> TXIStreamDownloader: startDownload
TXCStreamDownloader -> TXCFLVDownloader: startDownload
TXCFLVDownloader --> TXCFLVDownloader: processMsgRecvData

participant "Native" as Native #gray
TXCFLVDownloader -> Native: nativeParseData
TXCFLVDownloader -> Native: nativeGetVideoBytes
TXCFLVDownloader -> Native: nativeGetAudioBytes
TXCFLVDownloader -> Native: nativeGetVideoGop

participant "StreamRecvThread.cpp" as StreamRecvThread #gray
Native -> StreamRecvThread: writeData
StreamRecvThread -> StreamRecvThread: threadLoop

participant "FlvContainer.cpp" as FlvContainer #gray
StreamRecvThread -> FlvContainer: readTag
FlvContainer -> FlvContainer: readTagData
FlvContainer -> FlvContainer: parseVideoData


Native --> TXIStreamDownloader: onRecvAudioData
TXIStreamDownloader -> TXCStreamDownloader: onPullAudio
TXCStreamDownloader -> IDownloaderCallback: onPullAudio
TXCStreamDownloader -> TXIStreamDownloader: PushAudioFrame
TXIStreamDownloader -> Native: PushAudioFrame

Native --> TXIStreamDownloader: onRecvVideoData
TXIStreamDownloader -> TXCStreamDownloader: onPullNAL
TXCStreamDownloader -> IDownloaderCallback: onPullNAL
IDownloaderCallback -> TXCRenderAndDec: decVideo
TXIStreamDownloader -> Native: PushVideoFrame

@enduml