@startuml
class Route{
    String type
    Map<String, Object> params
}

enum RouteType {
    NATIVE("native")
    RN_PAGE("rn_page")
    WEB("web")
}

class RouteHandler{
    + boolean handle(Route route)
}
note right: 策略模式

class NativePageRouteHandler{
    + String pageName
}

class RNPageRouteHandler{

}

class WebPageRouteHandler{

}

class RouteController{
    - List<RouteHandler> handler
    - void registRouteHandler()
    + void parseRoute(Route route)
}

RouteHandler <|-- NativePageRouteHandler
RouteHandler <|-- RNPageRouteHandler
RouteHandler <|-- WebPageRouteHandler

RouteHandler *-- Route

RouteController *-- RouteHandler
RouteController <-- Route
RouteController <-- RouteType

@enduml