@startuml

== IP绑定 ==
采集端 -> 采集端: 生成IP二维码
推流端 -> 采集端: 扫码
== Socket连接 ==
推流端 -> 采集端: Socket连接
采集端 -> 推流端: Socket连接成功
== 指令：开始推流 ==
推流端 -> 采集端: Socket：开始推流
采集端 -> 采集端: 启动RSTP服务，推流
采集端 -> 推流端: Socket：推流成功
== RSTP ==
推流端 -> 采集端: RSTP：拉流
采集端 -> 推流端: RSTP：返回流
== 指令：摄像头切换 ==
推流端 -> 采集端: Socket：摄像头切换
采集端 -> 采集端: 摄像头切换
采集端 -> 推流端: Socket：摄像头切换成功
== 指令：结束推流 ==
推流端 -> 采集端: Socket：结束推流
采集端 -> 采集端: 停止RSTP服务
采集端 -> 推流端: Socket：结束推流成功
@enduml